using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Commerce.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddCategoriesTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Categories",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Slug = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
                    Description = table.Column<string>(type: "text", nullable: true),
                    ImageUrl = table.Column<string>(type: "text", nullable: true),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
                    DisplayOrder = table.Column<int>(type: "integer", nullable: false, defaultValue: 0),
                    ParentId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "CURRENT_TIMESTAMP"),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false, defaultValueSql: "CURRENT_TIMESTAMP")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Categories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Categories_Categories_ParentId",
                        column: x => x.ParentId,
                        principalTable: "Categories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Categories_ParentId",
                table: "Categories",
                column: "ParentId");

            migrationBuilder.CreateIndex(
                name: "IX_Categories_Slug",
                table: "Categories",
                column: "Slug",
                unique: true);

            // Seed initial categories
            var electronicsId = Guid.NewGuid();
            var clothingId = Guid.NewGuid();
            var homeId = Guid.NewGuid();
            var booksId = Guid.NewGuid();

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name", "Slug", "Description", "IsActive", "DisplayOrder", "CreatedAt", "UpdatedAt" },
                values: new object[,]
                {
                    { electronicsId, "Electronics", "electronics", "Electronic devices and accessories", true, 1, DateTime.UtcNow, DateTime.UtcNow },
                    { clothingId, "Clothing", "clothing", "Men's and Women's Clothing", true, 2, DateTime.UtcNow, DateTime.UtcNow },
                    { homeId, "Home & Garden", "home-garden", "Everything for your home and garden", true, 3, DateTime.UtcNow, DateTime.UtcNow },
                    { booksId, "Books", "books", "Physical and digital books", true, 4, DateTime.UtcNow, DateTime.UtcNow }
                });
                
            // Ensure Products table foreign key exists or is correct
            // Note: If the column already exists but points effectively to nowhere, we might need to recreate the FK constraint
            // The earlier error 42P01 "relation Categories does not exist" suggests the FK constraint might exist but the table doesn't,
            // OR the query is generated by EF because it thinks the relationship exists.
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Categories");
        }
    }
}
